export function Groups(){
    return (
        <section>
            <table>
                <tr>
                    <th>Classificação</th>
                    <th>P</th>
                    <th>J</th>
                    <th>V</th>
                    <th>E</th>
                    <th>D</th>
                    <th>GP</th>
                </tr>
                <tr>
                    <td>Brasil</td>
                    <td>3</td>
                    <td>9</td>
                    <td>3</td>
                    <td>0</td>
                    <td>0</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>Argentina</td>
                    <td>3</td>
                    <td>6</td>
                    <td>3</td>
                    <td>0</td>
                    <td>1</td>
                    <td>10</td>
                </tr>
            </table>
        </section>
    )
}